<?php

/** JavaScripts * */
$f->windowTitle("Adicionar Articulo / Material", "1.1");
$f->windowCenter();
$f->eClick("cancelar" . $f->id, ""
        . "new MUI.Audio({\"audio\":\$(AudioGlobal),\"src\":\"modulos/inventarios/multimedia/audios/window-close.mp3\",\"autoplay\":true});"
        . "MUI.closeWindow($('" . $f->ventana . "'));"
        . "");
$f->JavaScript(""
        . "function changeFamilia" . $f->id . "(){"
        . "     var fid='" . $f->id . "';"
        . "     var select=$('articulo'+fid);"
        . "     var familia=$('familia'+fid).getElement(':selected').value;"
        . "     new Request.JSON({"
        . "          url:'modulos/inventarios/formularios/detalle/salida/solicitud/crear/jsons/articulos.json.php',"
        . "          data:'familia='+familia,"
        . "          onRequest: function(){"
        . "             select.empty();"
        . "          },onComplete: function(json) {"
        . "             if($('familia'+fid)){"
        . "                 var length=json.length;"
        . "                 for(var i=0;i<length;i++){"
        . "                     var option=new Element('option', {'value':json[i].articulo,'text':json[i].nombre});"
        . "                     select.append(option);"
        . "                 }"
        . "             }else{"
        . "                     console.log('Indefinida: familia'+fid);"
        . "             }"
        . "          }"
        . "      }).send();"
        . "}"
        . "");

$f->JavaScript(""
        . "\nfunction changeArticulo" . $f->id . "(){"
        . "\n     var fid='" . $f->id . "';"
        . "\n     var _medida=$('medida');"
        . "\n     var medida=$('medida'+fid);"
        . "\n     var articulo=$('articulo'+fid);"
        . "\n     new Request.JSON({"
        . "\n          url:'modulos/inventarios/formularios/detalle/salida/solicitud/crear/jsons/articulo.json.php',"
        . "\n          data:'articulo='+articulo.value,"
        . "\n          onRequest: function(){"
        . "\n             medida.empty();"
        . "\n          },onComplete: function(json) {"
        . "\n             if($('articulo'+fid)){"
        . "\n                 var length=json.length;"
        . "\n                 for(var i=0;i<length;i++){"
        . "\n                     _medida.value=(json[i].medida);"
        . "\n                     medida.value=(json[i].medida);"
        . "\n                 }"
        . "\n             }else{"
        . "\n                   console.log('Indefinida: Articulo'+fid);"
        . "\n             }"
        . "\n          }"
        . "\n      }).send();"
        . "\n}"
        . "");
?>